spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost  #配置redis的主机地址，需要修改成自己的
    database: 0
    port: 6379
    password: redis123456
    jedis:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值也是0。
        # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException
  main:
    allow-bean-definition-overriding: true

  ## email
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1847714996@qq.com
    password: yxwytbgxhwbpfcff
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
#    url: jdbc:mysql://localhost:3357/myblog_dev?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    url: jdbc:mysql://182.42.112.115:3306/myblog_dev?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 443
  servlet:
    context-path: /api
  ssl:
    key-store: classpath:5670151_superarilo.icu.jks
    enabled: true
    key-store-password: saP88oIo
    keyStoreType: JKS
#  ssl:
#    key-store: classpath:caoguirong.jks
#    enabled: true
#    key-store-password: lzjFMku1
#    keyStoreType: JKS

mybatis-plus:
  mapper-locations: classpath:myblog/mapper/**/*.xml
  type-aliases-package: online.superarilo.myblog.entity, online.superarilo.myblog.vo

logging:
  level:
    online.superarilo.myblog.mapper: debug


## upload file adress
uploadFileAddress:
  ## windows
  windows_base_path: d:/upload/temp/
  ## linux
  linux_base_path: /usr/local/temp/
  ## picture server
  picture_server_base_path: /

## picture server:
pictureServer:
  host: 1.116.88.15
  port: 21
  user: ftpadmin
  password: admin123456

## http
pictureHttp: https://www.itrong.love:4433/
