spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: beta.superarilo.icu  #配置redis的主机地址，需要修改成自己的
    database: 0
    port: 12120
    password: XPW5mJ48LG4sP3nD
    jedis:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值也是0。
        # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException
  main:
    allow-bean-definition-overriding: true

  ## email
  mail:
    default-encoding: utf-8
    host: smtp.189.cn
    port: 587
    username: superarilo@189.cn
    password: WangHao1812
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    ## self-define
    title-template: "??? 是您的验证码"
    content-template:
      "<div>\
        <p>Hi，亲爱的玩家</p>\
        <p>你正在注册凡尔赛小镇的账号，验证码为：<b style='text-decoration:underline;'>???</b></p>\
        <p>请在5分钟内完成验证</p>\
        <p><b>SuperArilo</b></p>\
        <p>此为系统邮件，切勿回复</p>\
      </div>"


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://beta.superarilo.icu:3306/myblog_dev?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: 01c2502fa37f4127
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 3090
  servlet:
    context-path: /api
  #  ssl:
  #    key-store: classpath:5670151_superarilo.icu.jks
  #    enabled: true
  #    key-store-password: saP88oIo
  #    keyStoreType: JKS
#  ssl:
#    key-store: classpath:caoguirong.jks
#    enabled: true
#    key-store-password: lzjFMku1
#    keyStoreType: JKS

mybatis-plus:
  mapper-locations: classpath:myblog/mapper/**/*.xml
  type-aliases-package: online.superarilo.myblog.entity, online.superarilo.myblog.vo
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    online.superarilo.myblog.mapper: debug

## 分页属性
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true



## upload file adress
uploadFileAddress:
  ## picture server
  picture_server_base_path: /

## picture server:
pictureServer:
  #  host: 182.42.112.115
  host: 1.116.88.15
  port: 21
  user: ftpadmin
  password: admin123456

## http
#pictureHttp: https://www.superarilo.icu:4433/
pictureHttp: https://1.116.88.15:4433/


## user default-header.png url
user:
  default-header:
    url: http://image.superarilo.icu/image/default-header.png

## 七牛云
seven_niu_yun:
  AccessKey: cD_YA59Ok0Ti2yjLwfbyYh0lWigPUTyvSjcTc236
  SecretKey: Bx7hEkYh8r6mefK16XWQ4UocqU789PMJYL2mlp2v
  bucket: superarilo
  httpUrl: http://image.superarilo.icu/
  fileUri: image/

